### ISSUE TITLE
Develop REF Explorer software

### ISSUE THREAD

**Issue by SimonHettrick** [softwaresaved/ref-2021-analysis#31]
# Q1 

- [ ] Create outline plan
- [ ] Begin development
- [ ] Decide on financing approach
- [ ] Decide on dissemination plan

# Q2

- [ ] Develop prototype
- [ ] Decide on partners and what level of ownership they should have
- [ ] Test protoype and collect feedback
- [ ] Determine whether to leave as a low TRL tool or invest further time to create more mature software

**Comment by selina-aragon** [comment]
On hold.
